#!/bin/bash
# Generates the Homebrew cask for adlawson/homebrew-tap.
#
# The sha256 has to match the asset the cask actually downloads, so point --zip
# at either the local artifact from build-release.sh or the published release URL.
set -euo pipefail
cd "$(dirname "$0")/.."

APP_NAME="Legenda"
CASK_NAME="legenda"
REPO="adlawson/legenda"
# Keep in step with build-release.sh and Resources/Info.plist.
BUNDLE_ID="com.adlawson.legenda"

version=""
zip_arg=""
while test $# -gt 0; do
    case $1 in
        --version) version="$2"; shift 2;;
        --zip) zip_arg="$2"; shift 2;;
        *) echo "Unknown arg $1" >/dev/stderr; exit 1;;
    esac
done

if test -z "$version"; then echo "--version is mandatory" >/dev/stderr; exit 1; fi
if test -z "$zip_arg"; then echo "--zip is mandatory (a path or an https URL)" >/dev/stderr; exit 1; fi
version="${version#v}"

if test -f "$zip_arg"; then
    zip_file="$zip_arg"
elif grep -q '^https\?://' <<<"$zip_arg"; then
    zip_file="/tmp/${APP_NAME}-cask-tmp.zip"
    rm -f "$zip_file"
    curl -fsSL "$zip_arg" -o "$zip_file"
else
    echo "$zip_arg is neither a file nor an http(s) URL" >/dev/stderr
    exit 1
fi

sha="$(shasum -a 256 "$zip_file" | awk '{print $1}')"

mkdir -p .release

# Writes one cask. $1 is the token, which must match the filename or `brew readall`
# rejects it; $2 is the output path; $3 is "rolling" or "pinned".
#
# The differing stanza is emitted by a case below rather than passed in as a
# string: building it with a heredoc inside `$( )` breaks bash's parser, which
# reads an apostrophe in the heredoc body as an opening quote.
emit_cask() {
    local token="$1" output="$2" kind="$3"
    cat >"$output" <<EOF
cask "$token" do # THE FILE IS GENERATED BY script/build-brew-cask.sh
  version "$version"
  sha256 "$sha"

  url "https://github.com/$REPO/releases/download/v#{version}/${APP_NAME}-v#{version}.zip"
  name "$APP_NAME"
  desc "Menubar meeting timer that keeps a meeting to its agenda"
  homepage "https://github.com/$REPO"

EOF

    case "$kind" in
    rolling)
        cat >>"$output" <<EOF
  # Versions are dates, which the default git strategy does not match: its regex
  # only recognises dotted versions, so it would report an older semver tag as the
  # newest release and fail \`brew audit --online\`.
  livecheck do
    url "https://github.com/$REPO.git"
    strategy :git
    regex(/^v?(\d{8}(?:-[0-9a-z.]+)?)\$/i)
  end

EOF
        ;;
    pinned)
        cat >>"$output" <<EOF
  # Pinned to one release, so there is nothing to look for. Without this skip the
  # livecheck would resolve the newest tag, disagree with the version above, and
  # fail \`brew audit --online\`.
  livecheck do
    skip "Pinned release; the $CASK_NAME cask tracks the newest version"
  end

  # Both casks install the same app, so only one can be present at a time.
  conflicts_with cask: "$CASK_NAME"
EOF
        ;;
    *)
        echo "Unknown cask kind: $kind" >/dev/stderr
        exit 1
        ;;
    esac

    # No blank line here: each branch above supplies its own separator, because
    # conflicts_with and depends_on are in the same stanza group and brew style
    # rejects a blank line between them, while livecheck is a group of its own and
    # requires one.
    cat >>"$output" <<EOF
  # A bare symbol already means ">=" — the string form is deprecated.
  depends_on macos: :sonoma # macOS 14

  app "${APP_NAME}-v#{version}/${APP_NAME}.app"

  # Ad-hoc signed rather than notarised, so macOS would otherwise refuse the
  # first launch. must_succeed is false because the attribute is absent when the
  # zip did not come from a browser download.
  postflight do
    system_command "/usr/bin/xattr",
                   args:         ["-dr", "com.apple.quarantine", "#{appdir}/${APP_NAME}.app"],
                   must_succeed: false
  end

  zap trash: "~/Library/Preferences/${BUNDLE_ID}.plist"
end
EOF
    echo "wrote $output"
}

# The rolling cask always points at the newest release; the pinned one is immutable
# once published, so a version can be held.
rolling=".release/${CASK_NAME}.rb"
pinned=".release/${CASK_NAME}@${version}.rb"
emit_cask "$CASK_NAME" "$rolling" rolling
emit_cask "${CASK_NAME}@${version}" "$pinned" pinned

echo
cat "$rolling"
