#!/bin/bash
# Builds a distributable Legenda.app and zips it for a GitHub release.
#
# The zip's layout is Legenda-v<version>/Legenda.app, which is what the cask
# generated by build-brew-cask.sh expects.
set -euo pipefail
cd "$(dirname "$0")/.."

APP_NAME="Legenda"
BUNDLE_ID="com.adlawson.legenda"

version="${1:-}"
if test -z "$version"; then
    echo "usage: $0 <version>    e.g. $0 0.1.0" >/dev/stderr
    exit 1
fi
version="${version#v}"  # tolerate being handed a tag name

out=".release"
stage="$out/${APP_NAME}-v${version}"
bundle="$stage/${APP_NAME}.app"

rm -rf "$out"
mkdir -p "$bundle/Contents/MacOS" "$bundle/Contents/Resources"

# Universal, so the cask installs on Intel as well as Apple silicon. Note this
# lands in a different path from a single-arch build's .build/release/.
swift build -c release --arch arm64 --arch x86_64
cp ".build/apple/Products/Release/$APP_NAME" "$bundle/Contents/MacOS/$APP_NAME"
cp Resources/Info.plist "$bundle/Contents/Info.plist"

plist="$bundle/Contents/Info.plist"
/usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $version" "$plist"
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $version" "$plist"
/usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $BUNDLE_ID" "$plist"

# Ad-hoc signature: there's no Developer ID, so this is not notarised and macOS
# will quarantine the download. The cask strips that flag on install.
codesign --force --sign - "$bundle"
codesign --verify --strict "$bundle"

# ditto rather than zip: it preserves the bundle's symlinks and metadata.
# No --sequesterRsrc, which would add a __MACOSX/ directory of resource-fork
# stubs the bundle has no use for.
(cd "$out" && ditto -c -k --keepParent \
    "${APP_NAME}-v${version}" "${APP_NAME}-v${version}.zip")

zip="$out/${APP_NAME}-v${version}.zip"
echo
echo "built   $zip"
echo "arches  $(lipo -archs "$bundle/Contents/MacOS/$APP_NAME")"
echo "sha256  $(shasum -a 256 "$zip" | awk '{print $1}')"
