#!/bin/bash
# Generates the Homebrew cask for adlawson/homebrew-tap.
#
# The sha256 has to match the asset the cask actually downloads, so point --zip
# at either the local artifact from build-release.sh or the published release URL.
set -euo pipefail
cd "$(dirname "$0")/.."

APP_NAME="Legenda"
CASK_NAME="legenda"
REPO="adlawson/legenda"

version=""
zip_arg=""
while test $# -gt 0; do
    case $1 in
        --version) version="$2"; shift 2;;
        --zip) zip_arg="$2"; shift 2;;
        *) echo "Unknown arg $1" >/dev/stderr; exit 1;;
    esac
done

if test -z "$version"; then echo "--version is mandatory" >/dev/stderr; exit 1; fi
if test -z "$zip_arg"; then echo "--zip is mandatory (a path or an https URL)" >/dev/stderr; exit 1; fi
version="${version#v}"

if test -f "$zip_arg"; then
    zip_file="$zip_arg"
elif grep -q '^https\?://' <<<"$zip_arg"; then
    zip_file="/tmp/${APP_NAME}-cask-tmp.zip"
    rm -f "$zip_file"
    curl -fsSL "$zip_arg" -o "$zip_file"
else
    echo "$zip_arg is neither a file nor an http(s) URL" >/dev/stderr
    exit 1
fi

sha="$(shasum -a 256 "$zip_file" | awk '{print $1}')"

mkdir -p .release
cask=".release/${CASK_NAME}.rb"
cat >"$cask" <<EOF
cask "$CASK_NAME" do # THE FILE IS GENERATED BY script/build-brew-cask.sh
  version "$version"
  sha256 "$sha"

  url "https://github.com/$REPO/releases/download/v#{version}/${APP_NAME}-v#{version}.zip"
  name "$APP_NAME"
  desc "Menubar meeting timer that keeps a meeting to its agenda"
  homepage "https://github.com/$REPO"

  depends_on macos: ">= :sonoma" # macOS 14

  app "${APP_NAME}-v#{version}/${APP_NAME}.app"

  # Ad-hoc signed rather than notarised, so macOS would otherwise refuse the
  # first launch. must_succeed is false because the attribute is absent when the
  # zip did not come from a browser download.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/${APP_NAME}.app"],
                   must_succeed: false
  end

  zap trash: [
    "~/Library/Preferences/com.andrewlawson.legenda.plist",
  ]
end
EOF

echo "wrote $cask"
echo
cat "$cask"
